language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

cache: pip

install:
  - pip install --upgrade pip setuptools
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - python setup.py install

script:
  - pytest -rxXs -vv --cov pycantonese pycantonese
  - flake8 pycantonese
